version: 2
jobs:
  deploy_dev: # ジョブ名
    docker:
      - image: circleci/node:10.7 # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout # ソースコードのチェックアウト
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: npm install
          command: sudo npm install
      - run:
          name: lint check
          command: sudo npm install -g --save-dev eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
      - run:
          name: build
          command: sudo npm run build
      - run:
          name: sudo deploy to Firebase Hosting
          command: sudo ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project sasaki-portfolio

workflows:
  version: 2
  deploy_dev: # ワークフローの名前
    jobs:
      - deploy_dev: # 上で定義したジョブを指定します
          filters:
            branches:
              only: master # masterブランチのみを実行対象とします
