version: 2

jobs:
  deploy_dev: # ジョブ名
    docker:
      - image: circleci/node:10.7 # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout # ソースコードのチェックアウト
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: npm install
          command: npm install
      - run:
          name: 'Install Dependecies'
          command: npm install --save-dev firebase-tools
      - run:
          name: 'Install pkg'
          command: sudo npm install -g eslint eslint-config-prettier eslint-config-standard eslint-loader eslint-plugin-eslint-comments eslint-plugin-import eslint-plugin-jest eslint-plugin-node eslint-plugin-nuxt eslint-plugin-prettier eslint-plugin-promise eslint-plugin-standard eslint-plugin-vue @fortawesome/fontawesome-free @nuxtjs/eslint-config babel-eslint firebase-tools nodemon prettier stylus stylus-loader firebase-functions
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: 'Build Client Code'
          command: npm run build
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: npm install
          command: cd functions
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: npm install
          command: npm install
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project sasaki-portfolio

workflows:
  version: 2
  deploy_dev: # ワークフローの名前
    jobs:
      - deploy_dev: # 上で定義したジョブを指定します
          filters:
            branches:
              only: master # masterブランチのみを実行対象とします
